package no.nav.sbl.soknadsosialhjelp.json;

public class SoknadJsonTyper {
    public static final String BARNEBIDRAG = "barnebidrag";
    public static final String BOSTOTTE = "bostotte";
    public static final String STUDIELAN = "studielanOgStipend";
    public static final String JOBB = "jobb";
    public static final String SLUTTOPPGJOER = "sluttoppgjoer";
    public static final String BEKREFTELSE_SPARING = "sparing";
    public static final String BEKREFTELSE_UTBETALING = "utbetaling";
    public static final String BEKREFTELSE_VERDI = "verdi";
    public static final String BEKREFTELSE_BARNEUTGIFTER = "barneutgifter";
    public static final String BEKREFTELSE_BOUTGIFTER = "boutgifter";
    public static final String FORMUE_BRUKSKONTO = "brukskonto";
    public static final String FORMUE_BSU = "bsu";
    public static final String FORMUE_LIVSFORSIKRING = "livsforsikringssparedel";
    public static final String FORMUE_SPAREKONTO = "sparekonto";
    public static final String FORMUE_VERDIPAPIRER = "verdipapirer";
    public static final String FORMUE_ANNET = "belop";
    public static final String VERDI_BOLIG = "bolig";
    public static final String VERDI_CAMPINGVOGN = "campingvogn";
    public static final String VERDI_KJORETOY = "kjoretoy";
    public static final String VERDI_FRITIDSEIENDOM = "fritidseiendom";
    public static final String VERDI_ANNET = "annet";
    public static final String UTBETALING_SKATTEETATEN = "skatteetaten";
    public static final String UTBETALING_NAVYTELSE = "navytelse";
    public static final String UTBETALING_UTBYTTE = "utbytte";
    public static final String UTBETALING_SALG = "salg";
    public static final String UTBETALING_FORSIKRING = "forsikring";
    public static final String UTBETALING_ANNET = "annen";
    public static final String UTGIFTER_BARNEHAGE = "barnehage";
    public static final String UTGIFTER_SFO = "sfo";
    public static final String UTGIFTER_BARN_FRITIDSAKTIVITETER = "barnFritidsaktiviteter";
    public static final String UTGIFTER_BARN_TANNREGULERING = "barnTannregulering";
    public static final String UTGIFTER_ANNET_BARN = "annenBarneutgift";
    public static final String UTGIFTER_HUSLEIE = "husleie";
    public static final String UTGIFTER_STROM = "strom";
    public static final String UTGIFTER_KOMMUNAL_AVGIFT = "kommunalAvgift";
    public static final String UTGIFTER_OPPVARMING = "oppvarming";
    public static final String UTGIFTER_BOLIGLAN_AVDRAG = "boliglanAvdrag";
    public static final String UTGIFTER_BOLIGLAN_RENTER = "boliglanRenter";
    public static final String UTGIFTER_ANNET_BO = "annenBoutgift";
    public static final String UTGIFTER_ANDRE_UTGIFTER = "annen";
}