version: 2.1

jobs:
  build:
    docker:
    - image: circleci/openjdk:8u212-stretch
    steps:
    - checkout
    - restore_cache:
        name: Restore cached dependencies
        keys:
          - maven-{{ checksum "pom.xml" }}
    - run:
        name: Resolve/Update Dependencies
        command: mvn dependency:resolve
    - save_cache:
        name: Cache Maven dependencies
        key: maven-{{ checksum "pom.xml" }}
        paths:
          - ~/.m2
    - run:
        name: Build (and run tests)
        command: "mvn clean install"

  deploy:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - restore_cache:
        name: Restore cached dependencies
        keys:
          - maven-{{ checksum "pom.xml" }}
    - run:
        name: Decrypt GPG key for deployment til Maven Central
        command: "gpg --yes --batch --passphrase=$DECRYPT_GPG_KEY_PASSPHRASE codesigning.asc.gpg"
    - run:
        name: Import GPG private key to keyring
        command: "gpg --fast-import codesigning.asc"
    - run:
        name: Dummy task - list files in target directory
        command: "find ."

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
