package no.nav.sbl.soknadsosialhjelp.json

object SoknadJsonTyper {
    const val BARNEBIDRAG = "barnebidrag"
    const val BOSTOTTE = "bostotte"
    const val BOSTOTTE_SAMTYKKE = "bostotte_samtykke"
    const val STUDIELAN = "studielanOgStipend"
    const val JOBB = "jobb"
    const val SLUTTOPPGJOER = "sluttoppgjoer"
    const val BEKREFTELSE_SPARING = "sparing"
    const val BEKREFTELSE_UTBETALING = "utbetaling"
    const val BEKREFTELSE_VERDI = "verdi"
    const val BEKREFTELSE_BARNEUTGIFTER = "barneutgifter"
    const val BEKREFTELSE_BOUTGIFTER = "boutgifter"
    const val FORMUE_BRUKSKONTO = "brukskonto"
    const val FORMUE_BSU = "bsu"
    const val FORMUE_LIVSFORSIKRING = "livsforsikringssparedel"
    const val FORMUE_SPAREKONTO = "sparekonto"
    const val FORMUE_VERDIPAPIRER = "verdipapirer"
    const val FORMUE_ANNET = "belop"
    const val VERDI_BOLIG = "bolig"
    const val VERDI_CAMPINGVOGN = "campingvogn"
    const val VERDI_KJORETOY = "kjoretoy"
    const val VERDI_FRITIDSEIENDOM = "fritidseiendom"
    const val VERDI_ANNET = "annet"
    const val UTBETALING_SKATTEETATEN = "skatteetaten"
    const val UTBETALING_SKATTEETATEN_SAMTYKKE = "skatteetaten_samtykke"
    const val UTBETALING_NAVYTELSE = "navytelse"
    const val UTBETALING_UTBYTTE = "utbytte"
    const val UTBETALING_SALG = "salg"
    const val UTBETALING_FORSIKRING = "forsikring"
    const val UTBETALING_HUSBANKEN = "husbanken"
    const val UTBETALING_ANNET = "annen"
    const val UTGIFTER_BARNEHAGE = "barnehage"
    const val UTGIFTER_SFO = "sfo"
    const val UTGIFTER_BARN_FRITIDSAKTIVITETER = "barnFritidsaktiviteter"
    const val UTGIFTER_BARN_TANNREGULERING = "barnTannregulering"
    const val UTGIFTER_ANNET_BARN = "annenBarneutgift"
    const val UTGIFTER_HUSLEIE = "husleie"
    const val UTGIFTER_STROM = "strom"
    const val UTGIFTER_KOMMUNAL_AVGIFT = "kommunalAvgift"
    const val UTGIFTER_OPPVARMING = "oppvarming"
    const val UTGIFTER_BOLIGLAN_AVDRAG = "boliglanAvdrag"
    const val UTGIFTER_BOLIGLAN_RENTER = "boliglanRenter"
    const val UTGIFTER_ANNET_BO = "annenBoutgift"
    const val UTGIFTER_ANDRE_UTGIFTER = "annen"
}
