name: Code Analysis (CodeQL)

on:
  push:

jobs:
  analyze:
    name: "Run java/kotlin code analysis with CodeQL"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      ORG_GRADLE_PROJECT_githubUser: ${{ inputs.githubUser }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'java'
          config-file: navikt/sosialhjelp-ci/.github/codeql/codeql-config.yml@master

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build
        run: ./mvnw install -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:java"
