name: Code Analysis (CodeQL and Dependency Submission)

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

env:
  ORG_GRADLE_PROJECT_githubUser: ${{ inputs.githubUser }}
  ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

jobs:
  analyze:
    name: "Run java/kotlin code analysis with CodeQL"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'java'
          config-file: navikt/sosialhjelp-ci/.github/codeql/codeql-config.yml@main

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build
        run: ./mvnw install -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:java"

  dependencies:
    name: Dependency Submission
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_githubUser: x-access-token
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    permissions: # The Dependency Submission API requires write permission
      contents: write

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup Java with'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
